### ISSUE TITLE
tried this in 4.2 and got the follow error

### ISSUE THREAD

**Issue by scmsacit** [sebsoftnl/moodle-tool_tcpdffonts#3]
tried this in 4.2 and got the follow error Exception - syntax error, unexpected token "&lt;".
due to no install instructions i just unzip the folder and pasted TCPDFfonts folder into moodles mod folder

**Comment by rogiervandongen** [comment]
@scmsacit 
This is an admin tool and should be in /admin/tool/<tcpdffonts>

But the easier way would be to use the plugin installer in Moodle itself because it knows from the component name where it should reside in the Moodle folder tree.
